monolog:
    use_microseconds: false
    channels: [deprecation, security, register]
when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            changes:
                type: stream
                path: '%kernel.logs_dir%/changes.log'
                level: info
                formatter: 'monolog.formatter.line'
                channels: [app]
            login:
              formatter: 'monolog.formatter.line'
              type: stream
              path: '%kernel.logs_dir%/login.log'
              level: info
              channels: [security]
            register:
              formatter: 'monolog.formatter.line'
              type: stream
              path: '%kernel.logs_dir%/register.log'
              level: info
              channels: [register]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            register:
              formatter: 'monolog.formatter.line'
              type: stream
              path: '%kernel.logs_dir%/register.log'
              level: info
              channels: [ register ]
            changes:
                type: stream
                path: '%kernel.logs_dir%/changes.log'
                level: info
                channels:
                    - app
